.PHONY: clean All

All:
	@echo "----------Building project:[ GL_Ninja - Debug ]----------"
	@cd "GL_Ninja" && "$(MAKE)" -f  "GL_Ninja.mk" && "$(MAKE)" -f  "GL_Ninja.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ GL_Ninja - Debug ]----------"
	@cd "GL_Ninja" && "$(MAKE)" -f  "GL_Ninja.mk" clean
